2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_setup.py:_flush():67] Configure stats pid to 7499
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_setup.py:_flush():67] Loading settings from /home/kraskoa/.config/wandb/settings
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_setup.py:_flush():67] Loading settings from /home/kraskoa/Templates/25L/LLM/llm_25l_projekt/wandb/settings
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/kraskoa/Templates/25L/LLM/llm_25l_projekt/wandb/run-20250528_125617-4mphz44u/logs/debug.log
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/kraskoa/Templates/25L/LLM/llm_25l_projekt/wandb/run-20250528_125617-4mphz44u/logs/debug-internal.log
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x750ad0c51ba0>
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_init.py:init():761] calling init triggers
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-28 12:56:17,281 INFO    MainThread:7499 [wandb_init.py:init():784] starting backend
2025-05-28 12:56:17,282 INFO    MainThread:7499 [wandb_init.py:init():788] sending inform_init request
2025-05-28 12:56:17,283 INFO    MainThread:7499 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-28 12:56:17,283 INFO    MainThread:7499 [wandb_init.py:init():798] backend started and connected
2025-05-28 12:56:17,286 INFO    MainThread:7499 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-05-28 12:56:17,288 INFO    MainThread:7499 [wandb_init.py:init():891] updated telemetry
2025-05-28 12:56:17,291 INFO    MainThread:7499 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-05-28 12:56:17,970 INFO    MainThread:7499 [wandb_init.py:init():990] starting run threads in backend
2025-05-28 12:56:18,079 INFO    MainThread:7499 [wandb_run.py:_console_start():2375] atexit reg
2025-05-28 12:56:18,080 INFO    MainThread:7499 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-28 12:56:18,080 INFO    MainThread:7499 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-28 12:56:18,080 INFO    MainThread:7499 [wandb_run.py:_redirect():2315] Redirects installed.
2025-05-28 12:56:18,083 INFO    MainThread:7499 [wandb_init.py:init():1032] run started, returning control to user process
2025-05-28 12:56:18,085 INFO    MainThread:7499 [wandb_run.py:_config_callback():1261] config_cb None None {'return_dict': True, 'output_hidden_states': False, 'output_attentions': False, 'torchscript': False, 'torch_dtype': 'float32', 'use_bfloat16': False, 'tf_legacy_loss': False, 'pruned_heads': {}, 'tie_word_embeddings': True, 'chunk_size_feed_forward': 0, 'is_encoder_decoder': False, 'is_decoder': False, 'cross_attention_hidden_size': None, 'add_cross_attention': False, 'tie_encoder_decoder': False, 'max_length': 20, 'min_length': 0, 'do_sample': False, 'early_stopping': False, 'num_beams': 1, 'num_beam_groups': 1, 'diversity_penalty': 0.0, 'temperature': 1.0, 'top_k': 50, 'top_p': 1.0, 'typical_p': 1.0, 'repetition_penalty': 1.0, 'length_penalty': 1.0, 'no_repeat_ngram_size': 0, 'encoder_no_repeat_ngram_size': 0, 'bad_words_ids': None, 'num_return_sequences': 1, 'output_scores': False, 'return_dict_in_generate': False, 'forced_bos_token_id': None, 'forced_eos_token_id': None, 'remove_invalid_values': False, 'exponential_decay_length_penalty': None, 'suppress_tokens': None, 'begin_suppress_tokens': None, 'architectures': ['BertForMaskedLM'], 'finetuning_task': None, 'id2label': {0: 'Society & Culture', 1: 'Science & Mathematics', 2: 'Health', 3: 'Education & Reference', 4: 'Computers & Internet', 5: 'Sports', 6: 'Business & Finance', 7: 'Entertainment & Music', 8: 'Family & Relationships', 9: 'Politics & Government'}, 'label2id': {'Society & Culture': 0, 'Science & Mathematics': 1, 'Health': 2, 'Education & Reference': 3, 'Computers & Internet': 4, 'Sports': 5, 'Business & Finance': 6, 'Entertainment & Music': 7, 'Family & Relationships': 8, 'Politics & Government': 9}, 'tokenizer_class': None, 'prefix': None, 'bos_token_id': None, 'pad_token_id': 0, 'eos_token_id': None, 'sep_token_id': None, 'decoder_start_token_id': None, 'task_specific_params': None, 'problem_type': None, '_name_or_path': 'google-bert/bert-base-uncased', 'transformers_version': '4.52.1', 'gradient_checkpointing': False, 'model_type': 'bert', 'vocab_size': 30522, 'hidden_size': 768, 'num_hidden_layers': 12, 'num_attention_heads': 12, 'hidden_act': 'gelu', 'intermediate_size': 3072, 'hidden_dropout_prob': 0.1, 'attention_probs_dropout_prob': 0.1, 'max_position_embeddings': 512, 'type_vocab_size': 2, 'initializer_range': 0.02, 'layer_norm_eps': 1e-12, 'position_embedding_type': 'absolute', 'use_cache': True, 'classifier_dropout': None, 'output_dir': './results', 'overwrite_output_dir': False, 'do_train': False, 'do_eval': True, 'do_predict': False, 'eval_strategy': 'epoch', 'prediction_loss_only': False, 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 32, 'per_gpu_train_batch_size': None, 'per_gpu_eval_batch_size': None, 'gradient_accumulation_steps': 1, 'eval_accumulation_steps': None, 'eval_delay': 0, 'torch_empty_cache_steps': None, 'learning_rate': 1e-05, 'weight_decay': 0.01, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'adam_epsilon': 1e-08, 'max_grad_norm': 1.0, 'num_train_epochs': 10, 'max_steps': -1, 'lr_scheduler_type': 'linear', 'lr_scheduler_kwargs': {}, 'warmup_ratio': 0.0, 'warmup_steps': 0, 'log_level': 'passive', 'log_level_replica': 'warning', 'log_on_each_node': True, 'logging_dir': './logs', 'logging_strategy': 'epoch', 'logging_first_step': False, 'logging_steps': 500, 'logging_nan_inf_filter': True, 'save_strategy': 'epoch', 'save_steps': 500, 'save_total_limit': 2, 'save_safetensors': True, 'save_on_each_node': False, 'save_only_model': False, 'restore_callback_states_from_checkpoint': False, 'no_cuda': False, 'use_cpu': False, 'use_mps_device': False, 'seed': 42, 'data_seed': None, 'jit_mode_eval': False, 'use_ipex': False, 'bf16': False, 'fp16': True, 'fp16_opt_level': 'O1', 'half_precision_backend': 'auto', 'bf16_full_eval': False, 'fp16_full_eval': False, 'tf32': None, 'local_rank': 0, 'ddp_backend': None, 'tpu_num_cores': None, 'tpu_metrics_debug': False, 'debug': [], 'dataloader_drop_last': False, 'eval_steps': None, 'dataloader_num_workers': 0, 'dataloader_prefetch_factor': None, 'past_index': -1, 'run_name': './results', 'disable_tqdm': False, 'remove_unused_columns': True, 'label_names': None, 'load_best_model_at_end': True, 'metric_for_best_model': 'accuracy', 'greater_is_better': True, 'ignore_data_skip': False, 'fsdp': [], 'fsdp_min_num_params': 0, 'fsdp_config': {'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False}, 'fsdp_transformer_layer_cls_to_wrap': None, 'accelerator_config': {'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None}, 'deepspeed': None, 'label_smoothing_factor': 0.0, 'optim': 'adamw_torch', 'optim_args': None, 'adafactor': False, 'group_by_length': False, 'length_column_name': 'length', 'report_to': ['wandb'], 'ddp_find_unused_parameters': None, 'ddp_bucket_cap_mb': None, 'ddp_broadcast_buffers': None, 'dataloader_pin_memory': True, 'dataloader_persistent_workers': False, 'skip_memory_metrics': True, 'use_legacy_prediction_loop': False, 'push_to_hub': False, 'resume_from_checkpoint': None, 'hub_model_id': None, 'hub_strategy': 'every_save', 'hub_token': '<HUB_TOKEN>', 'hub_private_repo': None, 'hub_always_push': False, 'gradient_checkpointing_kwargs': None, 'include_inputs_for_metrics': False, 'include_for_metrics': [], 'eval_do_concat_batches': True, 'fp16_backend': 'auto', 'push_to_hub_model_id': None, 'push_to_hub_organization': None, 'push_to_hub_token': '<PUSH_TO_HUB_TOKEN>', 'mp_parameters': '', 'auto_find_batch_size': False, 'full_determinism': False, 'torchdynamo': None, 'ray_scope': 'last', 'ddp_timeout': 1800, 'torch_compile': False, 'torch_compile_backend': None, 'torch_compile_mode': None, 'include_tokens_per_second': False, 'include_num_input_tokens_seen': False, 'neftune_noise_alpha': None, 'optim_target_modules': None, 'batch_eval_metrics': False, 'eval_on_start': False, 'use_liger_kernel': False, 'eval_use_gather_object': False, 'average_tokens_across_devices': False}
2025-05-28 12:56:18,087 INFO    MainThread:7499 [wandb_config.py:__setitem__():154] config set model/num_parameters = 109489930 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x750ad07edd50>>
2025-05-28 12:56:18,087 INFO    MainThread:7499 [wandb_run.py:_config_callback():1261] config_cb model/num_parameters 109489930 None
2025-05-28 12:56:31,789 WARNING MsgRouterThr:7499 [router.py:message_loop():63] message_loop has been closed
Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-28 12:56:31,791 INFO    MsgRouterThr:7499 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-05-28 12:56:32,519 INFO    MainThread:7499 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-05-28 12:56:32,519 INFO    MainThread:7499 [wandb_init.py:_pause_backend():564] pausing backend
2025-05-28 12:56:46,217 INFO    MainThread:7499 [wandb_init.py:_resume_backend():569] resuming backend
2025-05-28 12:56:46,218 ERROR   MainThread:7499 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-28 12:56:46,229 ERROR   MainThread:7499 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 570, in _resume_backend
    self.backend.interface.publish_resume()
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 777, in publish_resume
    self._publish_resume(resume)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 293, in _publish_resume
    self._publish(rec)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-28 12:56:46,395 INFO    MainThread:7499 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-05-28 12:56:46,395 INFO    MainThread:7499 [wandb_init.py:_pause_backend():564] pausing backend
2025-05-28 12:56:46,395 ERROR   MainThread:7499 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-05-28 12:56:46,396 ERROR   MainThread:7499 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/IPython/core/events.py", line 82, in trigger
    func(*args, **kwargs)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 565, in _pause_backend
    self.backend.interface.publish_pause()
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 769, in publish_pause
    self._publish_pause(pause)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 289, in _publish_pause
    self._publish(rec)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/kraskoa/Templates/25L/LLM/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
